version: "3.9"
services:
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    build: ./backend
    command: npm start
    env_file:
      - ./backend/environment
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules